podTemplate(yaml: """
apiVersion: v1
kind: Pod
metadata:
  labels:
    label: pod
spec:
  containers:
  - name: kubectl
    image: 'lachlanevenson/k8s-kubectl:v1.8.8'
    command:
    - cat
    tty: true
"""
) {
    node(pod){
      container('kubectl'){
        sh "kubectl apply -f https://raw.githubusercontent.com/ceciliacalero/kubedeploy/master/ngnix-deployment.yml"
      }
    }
}